- .github/workflows/create-branch-on-issue.yml
<br/>
- issue 생성시 버그나서 발견한 현상 수정
- 도메인 추출 시 줄바꿈 문제를 고려하여 안정적으로 값 추출되도록 수정
- 브랜치 생성 기준 브랜치를 dev로 고정(기존 main)
- feature/{도메인}-{이슈번호} 형식의 브랜치명 생성
> feat: 이슈 기반 브랜치 자동 생성 워크플로 개선

- .github/workflows/create-branch-on-issue.yml
- .github/workflows/pr-lifecycle-alert.yml
main 브랜치에서 dev 브랜치로 최신 변경 사항을 반영하기 위한 PR입니다.
- main 브랜치 기준으로 dev 브랜치에 최신 내용 병합
- 설정 기능 구현 이후 버전 동기화 목적
- 이 PR은 직접 푸시할 수 없는 보호 브랜치 환경에서 dev를 최신화하기 위한 것입니다.
- 충돌이 없는 경우 바로 머지 가능합니다.
> sync: main → dev 브랜치 변경사항 반영

- build.gradle
- src/main/java/com/ddobang/backend/BackendApplication.java
- src/main/java/com/ddobang/backend/domain/region/controller/RegionController.java
- src/main/java/com/ddobang/backend/domain/region/dto/SubRegionsResponse.java
- src/main/java/com/ddobang/backend/domain/region/entity/Region.java
- src/main/java/com/ddobang/backend/domain/region/exception/RegionErrorCode.java
- src/main/java/com/ddobang/backend/domain/region/exception/RegionException.java
- src/main/java/com/ddobang/backend/domain/region/repository/RegionRepository.java
- src/main/java/com/ddobang/backend/domain/region/service/RegionService.java
- src/main/java/com/ddobang/backend/domain/store/controller/AdminStoreController.java
- src/main/java/com/ddobang/backend/domain/store/dto/StoreRequest.java
- src/main/java/com/ddobang/backend/domain/store/entity/Store.java
- src/main/java/com/ddobang/backend/domain/store/service/StoreService.java
- src/main/java/com/ddobang/backend/global/config/JpaAuditingConfig.java
- src/main/java/com/ddobang/backend/global/response/ResponseFactory.java
- src/main/resources/application-test.yml
- src/test/java/com/ddobang/backend/domain/region/controller/RegionControllerTest.java
- src/test/java/com/ddobang/backend/domain/region/repository/RegionRepositoryTest.java
- src/test/java/com/ddobang/backend/domain/region/service/RegionServiceTest.java
- src/test/java/com/ddobang/backend/domain/store/controller/AdminStoreControllerTest.java
- src/test/java/com/ddobang/backend/domain/store/repository/StoreRepositoryTest.java
- src/test/java/com/ddobang/backend/domain/store/service/StoreServiceTest.java
> feat: admin 전용 방탈출 매장 등록 구현

- src/main/java/com/ddobang/backend/domain/store/controller/AdminStoreController.java
- src/main/java/com/ddobang/backend/domain/store/dto/StoreRequest.java
- src/main/java/com/ddobang/backend/domain/store/entity/Store.java
- src/main/java/com/ddobang/backend/domain/store/service/StoreService.java
- src/main/java/com/ddobang/backend/domain/theme/entity/Theme.java
- src/main/java/com/ddobang/backend/domain/theme/entity/ThemeStats.java
- src/main/java/com/ddobang/backend/domain/theme/entity/ThemeTag.java
- src/main/java/com/ddobang/backend/global/validator/EnumValidator.java
- src/main/java/com/ddobang/backend/global/validator/ValidEnum.java
- src/test/java/com/ddobang/backend/domain/store/controller/AdminStoreControllerTest.java
- src/test/java/com/ddobang/backend/domain/store/repository/StoreRepositoryTest.java
- src/test/java/com/ddobang/backend/domain/store/service/StoreServiceTest.java
> feat: 매장 단건 수정, 삭제 api 구현 #23

- src/main/java/com/ddobang/backend/domain/member/entity/EvaluationKeyword.java
- src/main/java/com/ddobang/backend/domain/member/entity/Gender.java
- src/main/java/com/ddobang/backend/domain/member/entity/Member.java
- src/main/java/com/ddobang/backend/domain/member/entity/MemberReview.java
- src/main/java/com/ddobang/backend/domain/member/entity/MemberTag.java
<br/>
- 협업을 위한 베이스 작업 진행
- Member 엔티티 생성 및 Gender Enum 적용
- MemberTag 엔티티 생성 및 @ManyToMany 매핑 기반 구조 정의
- 매핑 테이블 별도 생성에 대한 소요 발생시 전환 계획
- MemberReview 엔티티 생성
- 평가 키워드 Enum(EvaluationKeyword) 정의
Closes #29
> feat: 사용자, 사용자 태그, 사용자 리뷰 도메인 엔티티 구현

- build.gradle
- src/main/java/com/ddobang/backend/domain/party/dto/request/PartyRequest.java
- src/main/java/com/ddobang/backend/domain/party/entity/Party.java
- src/main/java/com/ddobang/backend/domain/party/entity/PartyMember.java
- src/main/java/com/ddobang/backend/domain/party/types/PartyMemberStatus.java
- src/main/java/com/ddobang/backend/domain/party/types/PartyStatus.java
- src/main/java/com/ddobang/backend/global/config/QuerydslConfig.java
- src/main/java/com/ddobang/backend/global/response/SliceDto.java
- src/main/java/com/ddobang/backend/global/validation/annotation/ValidParticipants.java
- src/main/java/com/ddobang/backend/global/validation/validator/ParticipantsValidator.java
<br/>
- [v] 커밋 메세지를 컨벤션에 맞게 잘 적용 하였나요?
<br/>
- Party, PartyMember 엔티티 및 status enum 작성 및 ValidParticipants 어노테이션 구현
- queryDSL 의존성 추가 및 Q클래스 생성 디렉토리 설정
- 무한 스크롤을 위한 SliceDto 작성
다른 작업에 영향이 없을 것으로 보이는 파일들만 우선 업로드합니다.
내일 엔티티 병합이 완료되면 전체 변경 사항을 포함한 PR을 다시 올릴 예정입니다.
> feat: 모임 엔티티 및 기타 파일 작성

- src/main/java/com/ddobang/backend/domain/party/exception/PartyErrorCode.java
- src/main/java/com/ddobang/backend/domain/party/exception/PartyException.java
- src/main/java/com/ddobang/backend/global/exception/ServiceException.java
<br/>
<br/>
- 에러코드 추가 및 서비스익셉션 생성자 추가
> feat: 모임과 모임원 검증을 위한 에러 코드 추가

- .gitignore
- build.gradle
- src/main/java/com/ddobang/backend/global/security/jwt/JwtTokenProvider.java
- src/main/resources/application-secret.default.yml
- src/main/resources/application.yml
- src/test/java/com/ddobang/backend/global/security/jwt/JwtTokenProviderTest.java
<br/>
<br/>
- JWT 설정값(`secret`, 만료시간 등) 로딩 및 Key 초기화
- Access Token / Refresh Token 생성 메서드 구현
- 토큰에서 Subject 및 Claim 파싱 기능 구현
- 토큰 유효성 검증 메서드 구현
- JwtTokenProvider 단위 테스트 클래스 추가
Closes #18
> feat: JWT 토큰 생성 및 검증 유틸 클래스 구현

- src/main/java/com/ddobang/backend/global/security/SecurityConfig.java
- src/main/java/com/ddobang/backend/global/security/jwt/JwtAuthenticationFilter.java
- src/main/java/com/ddobang/backend/global/security/jwt/JwtTokenProvider.java
- src/main/java/com/ddobang/backend/global/util/CookieUtil.java
- src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
> fix: JWT인증 로직 오류 수정(헤더 > 쿠키), Role명 수정

- src/main/java/com/ddobang/backend/domain/party/controller/PartyController.java
- src/test/java/com/ddobang/backend/domain/party/controller/PartyControllerTest.java
> fix: 모임 검색필터 파라미터 -> 리퀘스트 바디 변경

- src/main/java/com/ddobang/backend/domain/diary/converter/DiaryConverter.java
- src/main/java/com/ddobang/backend/domain/diary/dto/request/DiaryFilterRequest.java
- src/main/java/com/ddobang/backend/domain/diary/dto/request/DiaryRequestDto.java
- src/main/java/com/ddobang/backend/domain/diary/entity/Diary.java
- src/main/java/com/ddobang/backend/domain/diary/exception/DiaryErrorCode.java
- src/main/java/com/ddobang/backend/domain/diary/service/DiaryService.java
- src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
- src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
<br/>
<br/>
- 탈출일지 코드 리뷰 기반 리팩토링
- OneToOne 문제는 멘토링 이후에 멘토님한테 확인 받고 수정하겠습니다. 현재는 MapsId를 통해 식별 관계 연결이 되어 있고, 테마 쪽 stat 입력 때문에 Embedded 객체로 전환하기에도 좀 애매한 것 같아서요.
- 탈출 사진은 이미지 업로드 시에 입력되므로 등록, 수정에서는 들어가지 않도록 수정하였습니다.
- 탈출 시간 중 남은 시간이 테마의 진행 시간보다 클 경우 예외 처리가 되도록 수정하였습니다.
> refactor: 코드 리뷰 기반 리팩토링

- src/main/java/com/ddobang/backend/domain/region/controller/RegionController.java
- src/main/java/com/ddobang/backend/domain/region/repository/RegionRepository.java
- src/main/java/com/ddobang/backend/domain/region/service/RegionService.java
- src/main/java/com/ddobang/backend/domain/theme/controller/ThemeController.java
- src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeFilterRequest.java
- src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeForAdminRequest.java
- src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeForMemberRequest.java
- src/main/java/com/ddobang/backend/domain/theme/dto/response/ThemeTagResponse.java
- src/main/java/com/ddobang/backend/domain/theme/entity/ThemeStat.java
- src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryImpl.java
- src/main/java/com/ddobang/backend/domain/theme/repository/ThemeTagRepository.java
- src/main/java/com/ddobang/backend/domain/theme/service/ThemeService.java
- src/main/java/com/ddobang/backend/domain/theme/service/ThemeTagService.java
- src/main/java/com/ddobang/backend/global/exception/GlobalErrorCode.java
- src/main/java/com/ddobang/backend/global/exception/GlobalExceptionHandler.java
- src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
- src/main/java/com/ddobang/backend/global/security/SecurityConfig.java
- src/test/java/com/ddobang/backend/domain/region/controller/RegionControllerTest.java
- src/test/java/com/ddobang/backend/domain/region/repository/RegionRepositoryTest.java
- src/test/java/com/ddobang/backend/domain/region/service/RegionServiceTest.java
- src/test/java/com/ddobang/backend/domain/theme/controller/ThemeControllerTest.java
- src/test/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryTest.java
- src/test/java/com/ddobang/backend/domain/theme/repository/ThemeTagRepositoryTest.java
- src/test/java/com/ddobang/backend/domain/theme/service/ThemeServiceTest.java
> feat: 테마 태그 목록 요청 로직 변경 및 테마 통계 낙관적 락 반영

- src/main/java/com/ddobang/backend/domain/party/controller/PartyController.java
- src/main/java/com/ddobang/backend/domain/party/repository/PartyRepositoryCustom.java
- src/main/java/com/ddobang/backend/domain/party/repository/PartyRepositoryImpl.java
- src/main/java/com/ddobang/backend/domain/party/service/PartyService.java
- src/test/java/com/ddobang/backend/domain/party/controller/PartyControllerTest.java
- src/test/java/com/ddobang/backend/domain/party/repository/PartyRepositoryTest.java
- src/test/java/com/ddobang/backend/domain/party/service/PartyServiceTest.java
> feat: 참여한 모임 목록 조회

- .github/workflows/deploy.yml
- Dockerfile
- infra/.gitignore
- infra/main.tf
- infra/secrets.tf.default
- infra/variables.tf
- src/main/java/com/ddobang/backend/domain/alarm/entity/AlarmType.java
- src/main/java/com/ddobang/backend/domain/alarm/service/AlarmService.java
- src/main/java/com/ddobang/backend/domain/board/listener/BoardAlarmListener.java
- src/test/java/com/ddobang/backend/domain/alarm/BoardAlarmListenerTest.java
> deploy: 확인용

- src/test/java/com/ddobang/backend/support/MemberTestFactory.java
<br/>
<br/>
- Member객체 테스트를 위한 공통 유저 케이스(MemberTestFactory) 입니다.
> test: MemberTestFactory 추가

- src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
> chore: 모임 초기데이터 생성

- src/main/java/com/ddobang/backend/domain/member/dto/response/BasicProfileResponse.java
- src/main/java/com/ddobang/backend/domain/member/dto/response/MemberReviewResponse.java
- src/main/java/com/ddobang/backend/domain/member/dto/response/OtherProfileResponse.java
- src/main/java/com/ddobang/backend/domain/member/entity/Member.java
- src/main/java/com/ddobang/backend/domain/member/entity/MemberReview.java
- src/main/java/com/ddobang/backend/domain/member/service/MemberReviewService.java
- src/test/java/com/ddobang/backend/domain/alarm/MessageAlarmIntegrationTest.java
- src/test/java/com/ddobang/backend/support/MemberTestFactory.java
> feat: 리뷰 작성시 회원 매너 점수 반영

- src/test/java/com/ddobang/backend/domain/party/service/PartyServiceTest.java
> test: 모임 생성 테스트에서 호스트 미등록 문제 해결

- src/main/java/com/ddobang/backend/domain/alarm/controller/AlarmController.java
- src/main/java/com/ddobang/backend/domain/message/controller/MessageController.java
- src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
> fix: 메세지 알람 멤버아이디부분 변경

- .github/workflows/deploy.yml
- src/main/java/com/ddobang/backend/domain/theme/dto/response/ThemeDetailResponse.java
- src/main/java/com/ddobang/backend/domain/theme/dto/response/ThemesResponse.java
- src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryImpl.java
- src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
- src/test/java/com/ddobang/backend/domain/theme/controller/ThemeControllerTest.java
<br/>
<br/>
- 테마 테스트 데이터 30개로 증가
- 테스트 데이터 증가로 인한 테스트 코드 수정
- 권장 인원 표기 방식 변경
- 최소 인원과 최대 인원을 유동적으로 입력할 수 있도록 
- 테마 인원수 필터링 로직 변경
> feat: 테마 권장 인원 표기 방식 변경 및 인원수 필터링 로직 변경
